# Generated by Django 6.0.5 on 2026-05-16 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="attendance",
            name="status",
            field=models.CharField(default="Present", max_length=20),
        ),
        migrations.AddField(
            model_name="marks",
            name="total_marks",
            field=models.IntegerField(default=100),
        ),
    ]
