# Generated by Django 6.0.5 on 2026-05-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0004_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
