# Generated by Django 6.0.5 on 2026-05-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0005_student_is_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="date",
        ),
        migrations.AddField(
            model_name="attendance",
            name="from_date",
            field=models.DateField(default="2026-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="to_date",
            field=models.DateField(default="2026-01-01"),
            preserve_default=False,
        ),
    ]
